[package]
name = "rqrr"
edition = "2018"
version = "0.1.0"
authors = ["WanzenBug <moritz9422@gmail.com>"]


[features]
img = ["image"]

[[test]]
name = "test_load"
path = "tests/test_load.rs"
required-features = ["img"]

[[test]]
name = "test_cap_find"
path = "tests/test_cap_find.rs"
required-features = ["img"]

[[bench]]
name = "bench_cap_find"
path = "benches/bench_cap_find.rs"
required-features = ["img"]
harness = false

[dev-dependencies]
criterion = "0.2"

[dependencies]
g2p = "0.3.1"

image = { version = "*", optional = true }
