[package]
name = "rqrr"
edition = "2018"
version = "0.1.0"
authors = ["WanzenBug <moritz9422@gmail.com>"]

[dev-dependencies]
qrcodegen = "1.3"

[dependencies]
piston = "*"
piston2d-graphics = "*"
pistoncore-glutin_window = "*"
piston2d-opengl_graphics = "*"
image = "*"
